services:
  app:
    build: .
    container_name: theses-checker
    expose: 
      - 8000
    ports:
      - "8000:8000"

    image: 1ukastesar/theses-checker
    restart: unless-stopped
    # user: '1000'

# networks:
#   default:
#     name: npm-proxy
#     external: true
