services:
  app:
    build: .
    container_name: theses-checker
    expose: 
      - 8000
    image: 1ukastesar/theses-checker
    restart: unless-stopped
    user: '1000'
    volumes:
      - ./:/app
      - ./src/web/staticfiles:/app/src/web/static
      - ./.env:/app/src/web/.env
  static:
    image: nginx
    container_name: theses-checker-static
    volumes:
      - ./src/web/staticfiles:/usr/share/nginx/html:ro
    restart: unless-stopped

networks:
  default:
    name: npm-proxy
    external: true
