services:
  app:
    build: .
    container_name: theses-checker-compose
    expose: 
      - 8001
    ports:
      - "8001:8001"

    image: 1ukastesar/theses-checker
    restart: unless-stopped
    # user: '1000'
    environment:
      ALLOWED_HOSTS: "127.0.0.1"
      PORT: "8001"
      

# networks:
#   default:
#     name: npm-proxy
#     external: true
